- hosts: localhost
  vars:
    source_key: ./.ssh/github_ed25519
    dest_key: '{{ lookup(''env'', ''HOME'') }}/.ssh/github_ed25519'
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - linux
    - name: Update Arch
      become: true
      community.general.pacman:
        upgrade: true
      tags:
        - arch
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/arch.yml
    - import_tasks: tasks/rust.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/dotfiles.yml
