- name: Install arch packages
  community.general.pacman:
    name:
      - alacritty
      - coreutils
      - cowsay
      - curl
      - fzf
      - gnupg
      - gnutls
      - go
      - htop
      - jq
      - ripgrep
      - tree
      - wget
      - kubectl
      - zsh
      - zstd
      - direnv
      - docker
      - fd
      - otf-comicshanns-nerd
      - lua
      - lua-language-server
      - neovim
      - python
      - scdoc
      - tmux
      - tree-sitter
      - vim
      - dmenu
      - base-devel
      - npm
      - i3
      # TODO: find replacements for these in Arch
      #- obsidian
      #- tflint
      #- yarn
      #- nodejs-lts-iron
    state: present
  become_user: root
  become: true
  tags:
    - arch
    - arch-test
- name: install Yay
  shell: |
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
    cd ..
    rm -rf yay
  tags:
    - arch
- name: Yay install packages
  shell: |
    yes | yay -S picom polybar feh rofi
  tags:
    - arch
    - arch-test
- name: Install 1password
  shell: |
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import
    git clone https://aur.archlinux.org/1password.git
    cd 1password
    yes | makepkg -si
    cd ..
    rm -rf 1password
  tags:
    - arch
