- name: Cloning .dotfiles
  git:
    repo: git@github.com:alexander-grieco/.dotfiles.git
    dest: '{{ lookup(''env'', ''HOME'') }}/.dotfiles'
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - dotfiles
- name: Stow dotfiles Mac
  shell: cd $HOME/.dotfiles && ./mac
  tags:
    - mac
- name: Stow dotfiles Arch
  shell: cd $HOME/.dotfiles && ./arch
  tags:
    - arch
