- name: Cloning .dotfiles
  git:
    repo: 'git@github.com:alexander-grieco/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./mac
  tags:
    - install
    - dotfiles
    - stow
