- name: Get output of where zsh is
  command: "which zsh"
  register: shell_output
  changed_when: false
  tags:
    - mac
    - core
    - dotfiles
    - linux
    - zsh

- name: Check if zsh is in /etc/shells
  command: "grep -q '{{ shell_output.stdout }}' /etc/shells"  # Replace with the path to your file
  ignore_errors: true
  register: grep_result
  tags:
    - mac
    - core
    - dotfiles
    - linux
    - zsh

- name: Add zsh to /etc/shells if it isn't present
  command: sudo sh -c 'echo "$(which zsh)" >> /etc/shells'
  when: grep_result.rc != 0 # If zsh isn't in /etc/shells
  tags:
    - mac
    - core
    - dotfiles
    - linux
    - zsh

- name: Change shell to zsh
  shell: sudo chsh -s $(which zsh)
  tags:
    - mac
    - core
    - dotfiles
    - linux
    - zsh
